project_id = "nexora-staging"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[auth]
enabled = true
site_url = "nexora://login-callback"
additional_redirect_urls = ["nexora://update-password"]
jwt_expiry = 3600
enable_signup = true

[edge_runtime]
enabled = true
policy = "per_worker"
inspector_port = 8083

[functions.request-verification-code]
verify_jwt = false

[functions.verify-email-code]
verify_jwt = false

[functions.register-consent]
verify_jwt = true
