import 'dart:async';

import 'package:flutter/material.dart';

import '../../market/data/binance_market_service.dart';
import '../../market/domain/candle.dart';
import '../data/pulse_ai_service.dart';
import '../domain/pulse_ai_consensus.dart';
import '../domain/pulse_engine.dart';
import '../domain/pulse_probability_calibrator.dart';
import '../domain/pulse_signal.dart';

class PulseScreen extends StatefulWidget { const PulseScreen({super.key}); @override State<PulseScreen> createState()=>_PulseScreenState(); }
class _PulseScreenState extends State<PulseScreen>{
 final _service=BinanceMarketService(); final _engine=const PulseEngine(); final _ai=const PulseAiService(); final _calibrator=const PulseProbabilityCalibrator();
 Timer? _clock,_refreshTimer,_syncTimer; Duration _binanceOffset=Duration.zero; DateTime? _roundStart,_roundEnd; PulseSignal? _signal; PulseAiConsensus? _aiPrediction; PulseProbabilityResult? _mathPrediction; bool _loading=true; String? _error; double? _startPrice;
 DateTime get _binanceNow=>DateTime.now().toUtc().add(_binanceOffset);
 @override void initState(){super.initState();_initialize();}
 Future<void> _initialize()async{await _syncBinanceClock();await _startCurrentRound();_clock=Timer.periodic(const Duration(seconds:1),(_){if(!mounted)return;final end=_roundEnd;if(end!=null&&!_binanceNow.isBefore(end)){_startCurrentRound();}else{setState((){});}});_refreshTimer=Timer.periodic(const Duration(seconds:5),(_)=>_load(silent:true));_syncTimer=Timer.periodic(const Duration(minutes:1),(_)=>_syncBinanceClock());}
 Future<void> _syncBinanceClock()async{try{final t=await _service.loadServerTime();_binanceOffset=t.difference(DateTime.now().toUtc());if(mounted)setState((){});}catch(_){}}
 Future<void> _startCurrentRound()async{final now=_binanceNow,m=(now.minute~/5)*5;_roundStart=DateTime.utc(now.year,now.month,now.day,now.hour,m);_roundEnd=_roundStart!.add(const Duration(minutes:5));_startPrice=null;_aiPrediction=null;_mathPrediction=null;if(mounted)setState((){});await _load();}
 Future<void> _load({bool silent=false})async{if(!silent&&mounted)setState((){_loading=true;_error=null;});try{final List<Candle> candles=await _service.loadCandles('BTCUSDT','1m',limit:40);final depth=await _service.loadDepthVolume('BTCUSDT',limit:100);double? startPrice=_startPrice;final start=_roundStart;if(start!=null){for(final c in candles.reversed){if(c.openTime.toUtc().millisecondsSinceEpoch==start.millisecondsSinceEpoch){startPrice=c.open;break;}}}final seconds=_roundEnd==null?300:_roundEnd!.difference(_binanceNow).inSeconds.clamp(0,300);final signal=_engine.analyze(candles:candles,bidVolume:depth.bidVolume,askVolume:depth.askVolume,roundStartPrice:startPrice,secondsRemaining:seconds);PulseProbabilityResult? mathPrediction;if(startPrice!=null){mathPrediction=_calibrator.calibrate(score:signal.score,instability:signal.instabilityScore,agreement:signal.agreementRatio,roundDistancePct:signal.roundDistancePct,expectedRemainingMovePct:signal.expectedRemainingMovePct,secondsRemaining:seconds);}PulseAiConsensus? aiPrediction;if(startPrice!=null){aiPrediction=await _ai.evaluate(symbol:'BTCUSDT',startPrice:startPrice,currentPrice:candles.last.close,secondsRemaining:seconds,quantitative:signal);}if(!mounted)return;setState((){_signal=signal;_mathPrediction=mathPrediction;_aiPrediction=aiPrediction;_startPrice=startPrice;_loading=false;_error=null;});}catch(e){if(!mounted)return;setState((){_loading=false;_error='No se pudo actualizar Predicciones minutos BTC.';});}}
 double get _fusedProbabilityUp{final m=_mathPrediction;if(m==null)return .5;final ai=_aiPrediction;if(ai==null||ai.direction==PulseDirection.noTrade)return m.probabilityUp;final aiP=ai.direction==PulseDirection.up?ai.confidence/100:1-ai.confidence/100;final signal=_signal;final instability=signal?.instabilityScore??50;final aiWeight=(.18*(1-instability/140)).clamp(.06,.18);return (m.probabilityUp*(1-aiWeight)+aiP*aiWeight).clamp(.08,.92).toDouble();}
 PulseDirection get _direction=>_fusedProbabilityUp>=.5?PulseDirection.up:PulseDirection.down;
 double get _confidence=>((_fusedProbabilityUp-.5).abs()+.5)*100;
 String get _directionLabel=>_direction==PulseDirection.up?'ALTA ↑':'BAJA ↓';
 String get _marketLabel{final s=_signal;if(s==null)return'Analizando mercado';return s.stability==MarketStability.stable?'Mercado estable':s.stability==MarketStability.unstable?'Mercado inestable':'Mercado muy inestable';}
 Duration get _remaining{final e=_roundEnd;if(e==null)return Duration.zero;final v=e.difference(_binanceNow);return v.isNegative?Duration.zero:v;}
 String get _countdown=>'${_remaining.inMinutes.toString().padLeft(2,'0')}:${_remaining.inSeconds.remainder(60).toString().padLeft(2,'0')}';
 double get _roundProgress=>(300-_remaining.inSeconds.clamp(0,300))/300;
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Predicciones minutos BTC')),body:RefreshIndicator(onRefresh:_startCurrentRound,child:ListView(padding:const EdgeInsets.all(20),children:[const Text('Predicción matemática calibrada de la dirección probable de Bitcoin al cierre de cada ronda de cinco minutos.',textAlign:TextAlign.center),const SizedBox(height:20),Card(child:Padding(padding:const EdgeInsets.all(20),child:Column(children:[const Text('TIEMPO RESTANTE',style:TextStyle(fontWeight:FontWeight.bold)),const SizedBox(height:8),Text(_countdown,style:const TextStyle(fontSize:46,fontWeight:FontWeight.bold)),const SizedBox(height:12),LinearProgressIndicator(value:_roundProgress.clamp(0,1)),const SizedBox(height:8),const Text('sincronizado con el reloj de Binance')]))),const SizedBox(height:14),Card(child:Padding(padding:const EdgeInsets.symmetric(horizontal:24,vertical:32),child:Column(children:[const Text('PREDICCIÓN BTC',style:TextStyle(fontWeight:FontWeight.bold)),const SizedBox(height:14),if(_loading&&_signal==null)const CircularProgressIndicator()else...[Text(_directionLabel,style:const TextStyle(fontSize:44,fontWeight:FontWeight.bold)),const SizedBox(height:18),Text('${_confidence.toStringAsFixed(1)}%',style:const TextStyle(fontSize:38,fontWeight:FontWeight.w700)),const SizedBox(height:4),Text(_mathPrediction==null?'calibrando datos':'probabilidad matemática fusionada')]]))),const SizedBox(height:14),Card(child:ListTile(leading:const Icon(Icons.insights),title:Text(_marketLabel,style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:const Text('La probabilidad se contrae hacia 50% cuando faltan evidencias, hay contradicción o aumenta la inestabilidad.'))),if(_error!=null)...[const SizedBox(height:14),Text(_error!,textAlign:TextAlign.center,style:TextStyle(color:Theme.of(context).colorScheme.error))],const SizedBox(height:18),const Text('Modelo experimental: regresión logística + difusión del precio + volatilidad + confluencia + microestructura + consenso de IA. La precisión debe validarse con rondas cerradas; no garantiza resultados.',textAlign:TextAlign.center)])));
 @override void dispose(){_clock?.cancel();_refreshTimer?.cancel();_syncTimer?.cancel();super.dispose();}
}
